#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\
frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 3848-web-01 54.90.153.236:80 check
	server 3848-web-02 35.237.95.39:80 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

