#!/usr/bin/env bash
# Run nginx as under the user 'nginx' that listens on port 8080
pkill -f "^/usr/sbin/apache2"
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-enabled/default
sudo -u nginx /usr/sbin/nginx
